name: Continues Integration
run-name: ${{ github.actor }} is ci out GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - master
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: '0'

      - name: Setup Java 25
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '25'

      - name: Run Test
        run: mvn test

      - name: Build Maven
        run: mvn clean package -DskipTests

