name: Slack Notify
run-name: Slack Notify
on:
  workflow_run:
    workflows:
      - Continuous Deployment
    types:
      - completed
    branches:
      - main
      - master

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}